[profile.default]
src = 'contracts'
out = 'out'
libs = ['lib']
solc = '0.8.24'
optimizer = true
optimizer_runs = 10_000
fs_permissions = [
  { access = "read-write", path = "./script/utils" }
]

[fuzz]
runs = 256